name: Build of pull request

on:
  - push

jobs:
  #   build:
  #     runs-on: ubuntu-latest
  #     steps:
  #       - name: Checkout
  #         uses: actions/checkout@v2
  #       - name: Use Node.js
  #         uses: actions/setup-node@v1
  #         with:
  #           always-auth: true
  #           node-version: '12.x'
  #           registry-url: https://npm.pkg.github.com
  #           scope: '@houseworksinc'

  #       - name: restore lerna
  #         uses: actions/cache@v2
  #         id: lerna-cache
  #         with:
  #           path: |
  #             node_modules
  #             */*/node_modules
  #           key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

  #       - name: Install root dependencies
  #         if: steps.lerna-cache.outputs.cache-hit != 'true'
  #         run: yarn
  #         env:
  #           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  #       - name: Run build
  #         run: yarn build

  e2e:
    #     needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download actions 
        #         run: mkdir e2e
        #       - name: Navigate to E2E folder
        #         run: cd ./e2e
        #       - name: Cloning automation repository
        #         run: git clone "https://github.com/houseworksinc/emr-frontend-automation.git"
        uses: actions/checkout@main
        # with:
          # repository: pankaj51/Pj-practice
      #           path: ./e2e
      - name: download pj repo
        uses: pankaj51/Pj-practice@main
        with: 
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.0-alpha - 3.9.0" # SemVer's version range syntax
      - name: Install requirements.txt
        run: pip install -r requirements.txt
      - name: Install robot framework
        run: pip install robotframework
      - name: Install robot framework selenium library
        run: pip install robotframework-seleniumlibrary
      - name: Install robot framework parallel bot
        run: pip install robotframework-pabot
      - name: Install robot framework webdriver manager for automatic driver download
        run: pip install webdriver-manager
      - name: Run tests
        run: robot .//feature//

